task: detect
mode: train
model: yolo11n.pt
data: dataset/data.yaml
epochs: 50
batch: 32
imgsz: 640
workers: 12

optimizer: AdamW
lr0: 0.001
lrf: 0.01
momentum: 0.937
weight_decay: 0.001

warmup_epochs: 2
warmup_momentum: 0.8
warmup_bias_lr: 0.1

hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
translate: 0.1
scale: 0.5
fliplr: 0.5
mosaic: 1.0
mixup: 0.1

patience: 20
save_period: 10
save: true
verbose: true
plots: true 