task: detect
mode: train
model: yolo11n.pt
data: dataset_balance/data.yaml
epochs: 80
batch: 24
imgsz: 832
workers: 8

optimizer: AdamW
lr0: 0.0007
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005

warmup_epochs: 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1

hsv_h: 0.02
hsv_s: 0.8
hsv_v: 0.5
translate: 0.15
scale: 0.6
fliplr: 0.5
mosaic: 0.5
mixup: 0.05

copy_paste: 0.2
erasing: 0.1

label_smoothing: 0.01

patience: 30
save_period: 10
save: true
verbose: true
plots: true